spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-db

loan-broker:
  http-adapter:
    outbound:
      bank1:
        url: http://localhost:8080/bank1/loan/inquiry
        spec: bank1spec.json
        enabled: true
      bank2:
        url: http://localhost:8080/bank2/loan/inquiry
        spec: bank2spec.json
        enabled: true
      creditbeauro:
        url: http://localhost:8080/credit/score/{pan}
        enabled: true
    inbound:
      loanInquiry:
        url: /inquiry
        enabled: true
